### ISSUE TITLE
covid19_samples_processed.csv out of date

### ISSUE THREAD

**Issue by edomt** [sebaxtian/colombia_covid_19_pipe#3]
Hi!

We're using your file `output/covid19_samples_processed.csv` to automate our data collection process for Colombia at https://www.ourworldindata.org
It seems this file doesn't include the latest week shown on https://www.ins.gov.co/Noticias/Paginas/Coronavirus.aspx (06/04 to 12/04). Would you mind updating it, if your automated pipeline still includes that variable?

Thank you!
Edouard

**Comment by sebaxtian** [comment]
Thanks a lot @edomt I going to review that issue, as a soon I have any comment or response I will let you know.

Thank you!
Sebaxtian

**Comment by sebaxtian** [comment]
Hi, @edomt now is updated, please check again and let me know if it works for you.

Last week:
06/04/2020-12/04/2020 | 15302 | 42987

https://github.com/sebaxtian/colombia_covid_19_pipe/blob/master/output/covid19_samples_processed.csv

**Comment by edomt** [comment]
Perfect, thank you @sebaxtian! :)

**Comment by sebaxtian** [comment]
Hi @edomt greetings 

The INS now has been reported the samples processed by day, then I did update the samples processed here:
https://github.com/sebaxtian/colombia_covid_19_pipe/blob/master/output/covid19co_samples_processed.csv

The first row has samples processed but doesn't exist date for that samples processed, the other rows have the accumulative samples processed and now is by day.

If you have any question let me know.

Thanks
